config/routes.rb
Rails.application.routes.draw do
  root to: "standings#index"
  resources :posses, only: [:index]
  resources :cups, only: [:index]
  get "/login", to: redirect("/auth/slack"), as: :login
  get "/logout", to: "sessions#destroy", as: :logout
  get "/auth/slack/callback" => "sessions#create"
  namespace :api do
    namespace :v1 do
      resources :commands, only: [:create]
      resources :posses, only: [:index]
    end
  end

  namespace :admin do
    resources :students
    resources :cups, only: [:new, :create]
  end
end

app/models/commands/student.rb
class Commands::Student < Commands::Base
  include ActionView::Helpers::TextHelper

  def response
    error_message || create_student
  end

  def error_message
    return unauthorized unless admin?
    return invalid_token unless token_valid?
    nil
  end

  def unauthorized
    { "json" => {"error" => "User not authorized."}, "status" => 401 }
  end

  def invalid_token
    { "json" => {"error" => "Invalid Token."}, "status" => 401 }
  end

  def create_student
    if text =~ /#pc Add student (.*) \((.*)\) to the (.*) posse/i
      student_name = $1
      student_login = $2
      posse_name = $3
      slack_login = student_login.match(/\@(\w+)/)[1]
      Rails.logger.info "Name: #{student_name}, #{student_login}, #{slack_login}, #{posse_name}"
      posse = Posse.where(name: posse_name).first_or_create
      Student.where(slack_uid: slack_login).first_or_create do |student|
        student.name = student_name
        student.posse = posse
      end
      {"json" => {"status" => "200", "text" => "#{student_name} added to the #{posse.name} posse."}}
    else
      {"json" => {"status" => "200", "text" => "Try: #pc Add student Joe Smith (@joesmith) to the Foo posse"}}
    end
  end

  def success_message
    "#{pluralize(amount, 'point')} awarded to #{posse.name} posse! Current score: #{posse.current_score}."
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :posse
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < Admin::BaseController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to admin_students_path
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    Student.find(params[:id]).update_attributes(student_params)
    redirect_to admin_students_path
  end

  def student_params
    params.require(:student).permit(:name, :slack_uid, :posse_id, :slack_name)
  end
end

app/views/admin/students/_form.html.erb
<%= form_for [:admin, student] do |f| %>
<%= f.label "Name" %>
<%= f.text_field "name" %>
<%= f.label "Slack ID" %>
<%= f.text_field "slack_uid" %>
<%= f.label "Slack Name" %>
<%= f.text_field "slack_name" %>
<%= f.label "Posse" %>
<select name="student[posse_id]">
  <% Posse.all.each do |posse| %>
    <% if student.posse_id && posse.id == student.posse_id %>
      <option selected value="<%= posse.id %>"><%= posse.name %></option>
     <% else %>
      <option value="<%= posse.id %>"><%= posse.name %></option>
    <% end %>
  <% end %>
</select>

<%= f.submit %>
<% end %>

app/views/admin/students/edit.html.erb
<h1>Edit Student: <%= @student.name %></h1>

<%= render partial: "admin/students/form", locals: {student: @student} %>

app/views/admin/students/index.html.erb
<h1>Posse Cup Students</h1>

<h3><%= link_to "New Student", new_admin_student_path %></h3>
<table>
  <tr>
    <th>Name</th>
    <th>Slack ID</th>
    <th>Slack Name</th>
    <th>Posse</th>
    <th>Edit</th>
  </tr>

  <% @students.each do |s| %>
  <tr>
    <td>Name: <%= s.name %></td>
    <td>Slack ID: <%= s.slack_uid %></td>
    <td>Posse: <%= s.posse.name if s.posse %></td>
    <td>Slack Name: <%= s.slack_name %></td>
    <td><%= link_to "Edit", edit_admin_student_path(s) %></td>
  </tr>
  <% end %>

</table>

app/views/admin/students/new.html.erb
<h1>New Student</h1>

<%= render partial: "admin/students/form", locals: {student: @student} %>